# Generated by Django 4.1.3 on 2022-11-30 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.IntegerField()),
                ('conta', models.IntegerField(unique=True)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total_pedido', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_total_a_pagar', models.DecimalField(decimal_places=2, max_digits=8)),
                ('qtd_parcelas', models.IntegerField()),
                ('data_pedido', models.DateField()),
                ('fk_conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.conta')),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(default=1, max_length=13, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nascimento',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Transferecia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
                ('tipo_transferencia', models.CharField(choices=[('P', 'PIX'), ('B', 'Boleto'), ('C', 'Bancária')], default='P', max_length=1)),
                ('valor_transferencia', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fk_pagador_conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_pagador_conta', to='users.conta')),
                ('fk_recebedor_conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_recebedor_conta', to='users.conta')),
            ],
        ),
        migrations.CreateModel(
            name='TentativaLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_acesso_errado', models.IntegerField()),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelaEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_vencimento', models.DateField()),
                ('fk_emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimo', to='users.emprestimo')),
            ],
        ),
        migrations.CreateModel(
            name='Extrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('titulo', models.CharField(max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fk_transferencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.transferecia')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=40)),
                ('bairro', models.CharField(max_length=30)),
                ('numero', models.CharField(max_length=6)),
                ('cidade', models.CharField(max_length=30)),
                ('pais', models.CharField(max_length=30)),
                ('CEP', models.IntegerField()),
                ('descricao_complemento', models.CharField(max_length=15)),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.IntegerField(null=True, unique=True)),
                ('celular', models.IntegerField(unique=True)),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='conta',
            name='fk_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('validade', models.DateField()),
                ('cvv', models.IntegerField(unique=True)),
                ('limite_credito', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fk_conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.conta')),
            ],
        ),
    ]
