# Generated by Django 4.1.3 on 2022-11-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_cartao_fk_conta_cartao_fk_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tentativalogin',
            name='hora',
        ),
        migrations.AlterField(
            model_name='tentativalogin',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
