# Generated by Django 4.1.3 on 2022-11-30 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_tentativalogin_hora_alter_tentativalogin_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tentativalogin',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
